# Setup
title:               p0wnyb0y
tagline:             'InfoSec For Life'
description:         'An information security blog.'
url:                 https://p0wnyb0y.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Emmett
  url:               https://twitter.com/p0wnyb0y
  email:             noemail@p0wnyb0y.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y